In [28]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
data = pd.read_csv("supply_chain_data.csv")

In [4]:
print(data.head())

  Product type   SKU      Price  Availability  Number of products sold  \
0     haircare  SKU0  69.808006            55                      802
1     skincare  SKU1  14.843523            95                      736
2     haircare  SKU2  11.319683            34                        8
3     skincare  SKU3  61.163343            68                       83
4     skincare  SKU4   4.805496            26                      871

   Revenue generated Customer demographics  Stock levels  Lead times  \
0        8661.996792            Non-binary            58           7
1        7460.900065                Female            53          30
2        9577.749626               Unknown             1          10
3        7766.836426            Non-binary            23          13
4        2686.505152            Non-binary             5           3

   Order quantities  ...  Location Lead time  Production volumes  \
0                96  ...    Mumbai        29                 215
1                37  ...    Mumbai        23                 517
2                88  ...    Mumbai        12                 971
3                59  ...   Kolkata        24                 937
4                56  ...     Delhi         5                 414

  Manufacturing lead time Manufacturing costs  Inspection results  \
0                      29           46.279879             Pending
1                      30           33.616769             Pending
2                      27           30.688019             Pending
3                      18           35.624741                Fail
4                       3           92.065161                Fail

   Defect rates  Transportation modes   Routes       Costs
0      0.226410                  Road  Route B  187.752075
1      4.854068                  Road  Route B  503.065579
2      4.580593                   Air  Route C  141.920282
3      4.746649                  Rail  Route A  254.776159
4      3.145580                   Air  Route A  923.440632

[5 rows x 24 columns]

In [5]:
print(data.describe())

            Price  Availability  Number of products sold  Revenue generated  \
count  100.000000    100.000000               100.000000         100.000000
mean    49.462461     48.400000               460.990000        5776.048187
std     31.168193     30.743317               303.780074        2732.841744
min      1.699976      1.000000                 8.000000        1061.618523
25%     19.597823     22.750000               184.250000        2812.847151
50%     51.239831     43.500000               392.500000        6006.352023
75%     77.198228     75.000000               704.250000        8253.976921
max     99.171329    100.000000               996.000000        9866.465458

       Stock levels  Lead times  Order quantities  Shipping times  \
count    100.000000  100.000000        100.000000      100.000000
mean      47.770000   15.960000         49.220000        5.750000
std       31.369372    8.785801         26.784429        2.724283
min        0.000000    1.000000          1.000000        1.000000
25%       16.750000    8.000000         26.000000        3.750000
50%       47.500000   17.000000         52.000000        6.000000
75%       73.000000   24.000000         71.250000        8.000000
max      100.000000   30.000000         96.000000       10.000000

       Shipping costs   Lead time  Production volumes  \
count      100.000000  100.000000          100.000000
mean         5.548149   17.080000          567.840000
std          2.651376    8.846251          263.046861
min          1.013487    1.000000          104.000000
25%          3.540248   10.000000          352.000000
50%          5.320534   18.000000          568.500000
75%          7.601695   25.000000          797.000000
max          9.929816   30.000000          985.000000

       Manufacturing lead time  Manufacturing costs  Defect rates       Costs
count                100.00000           100.000000    100.000000  100.000000
mean                  14.77000            47.266693      2.277158  529.245782
std                    8.91243            28.982841      1.461366  258.301696
min                    1.00000             1.085069      0.018608  103.916248
25%                    7.00000            22.983299      1.009650  318.778455
50%                   14.00000            45.905622      2.141863  520.430444
75%                   23.00000            68.621026      3.563995  763.078231
max                   30.00000            99.466109      4.939255  997.413450

In [6]:
data.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [16]:
data = data.drop_duplicates()

In [14]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    str
 1   SKU                      100 non-null    str
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    str
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    str
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    str
 14  Location                 100 non-null    str
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    str
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    str
 22  Routes                   100 non-null    str
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), str(9)
memory usage: 18.9 KB

In [9]:
data.rename(columns={
    'Lead times': 'Inventory Lead Time',
    'Lead time': 'Supplier Lead Time',
    'Manufacturing lead time': 'Manufacturing Lead Time'
}, inplace=True)

In [10]:
data.groupby("Product type")["Revenue generated"].sum().sort_values(ascending=False)

Product type
skincare     241628.162133
haircare     174455.390605
cosmetics    161521.265999
Name: Revenue generated, dtype: float64

In [11]:
data.groupby("Supplier name")["Defect rates"].mean().sort_values()

Supplier name
Supplier 1    1.803630
Supplier 4    2.337397
Supplier 2    2.362750
Supplier 3    2.465786
Supplier 5    2.665408
Name: Defect rates, dtype: float64

In [12]:
data[["Shipping times", "Shipping costs"]].corr()

                Shipping times  Shipping costs
Shipping times        1.000000        0.045108
Shipping costs        0.045108        1.000000

In [13]:
data[data["Stock levels"] == 0]

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Inventory Lead Time,Order quantities,...,Location,Supplier Lead Time,Production volumes,Manufacturing Lead Time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
68,haircare,SKU68,37.931812,29,163,3550.218433,Non-binary,0,8,58,...,Bangalore,2,375,18,97.113582,Fail,1.983468,Rail,Route A,299.706303

In [17]:
data.columns = data.columns.str.lower().str.replace(" ", "_")

In [18]:
data[["shipping_costs", "manufacturing_costs", "costs"]].describe()

       shipping_costs  manufacturing_costs       costs
count      100.000000           100.000000  100.000000
mean         5.548149            47.266693  529.245782
std          2.651376            28.982841  258.301696
min          1.013487             1.085069  103.916248
25%          3.540248            22.983299  318.778455
50%          5.320534            45.905622  520.430444
75%          7.601695            68.621026  763.078231
max          9.929816            99.466109  997.413450

In [19]:
data[["shipping_costs", "manufacturing_costs", "costs"]].head(10)

   shipping_costs  manufacturing_costs       costs
0        2.956572            46.279879  187.752075
1        9.716575            33.616769  503.065579
2        8.054479            30.688019  141.920282
3        1.729569            35.624741  254.776159
4        3.890548            92.065161  923.440632
5        4.444099            56.766476  235.461237
6        3.880763             1.085069  134.369097
7        2.348339            99.466109  802.056312
8        3.404734            11.423027  505.557134
9        7.166645            47.957602  995.929461

In [20]:
data[["shipping_costs", "manufacturing_costs", "costs"]].corr()

                     shipping_costs  manufacturing_costs     costs
shipping_costs             1.000000             0.005984  0.051671
manufacturing_costs        0.005984             1.000000 -0.013911
costs                      0.051671            -0.013911  1.000000

In [21]:
data.groupby("transportation_modes")["costs"].mean().sort_values()

transportation_modes
Sea     417.819148
Rail    541.747556
Road    553.385988
Air     561.712596
Name: costs, dtype: float64

In [22]:
data.groupby(["transportation_modes", "routes"])["costs"].mean()

transportation_modes  routes
Air                   Route A    527.353405
                      Route B    637.836861
                      Route C    542.347752
Rail                  Route A    485.050751
                      Route B    637.037340
                      Route C    456.936769
Road                  Route A    539.492010
                      Route B    552.391165
                      Route C    586.539277
Sea                   Route A    335.680631
                      Route B    564.338352
                      Route C    341.782748
Name: costs, dtype: float64

In [23]:
data.groupby("transportation_modes")["shipping_times"].mean()

transportation_modes
Air     5.115385
Rail    6.571429
Road    4.724138
Sea     7.117647
Name: shipping_times, dtype: float64

In [24]:
data["cost_efficiency"] = data["shipping_times"] / data["costs"]

In [25]:
data[["shipping_times", "costs", "cost_efficiency"]].head()

   shipping_times       costs  cost_efficiency
0               4  187.752075         0.021305
1               2  503.065579         0.003976
2               2  141.920282         0.014092
3               6  254.776159         0.023550
4               8  923.440632         0.008663

In [26]:
data.groupby("transportation_modes")["cost_efficiency"].mean().sort_values()

transportation_modes
Air     0.011688
Road    0.011853
Rail    0.016178
Sea     0.027163
Name: cost_efficiency, dtype: float64

In [27]:
data.to_csv("clean_supply_chain.csv", index=False)

In [29]:

engine = create_engine("mysql+pymysql://PASS@localhost/supply_chain_db")
data.to_sql("supply_chain", con=engine, if_exists="replace", index=False)

print("Data uploaded successfully!")

Data uploaded successfully!